### ISSUE TITLE
Dropbox connector does not show thumbnail preview in the details pane (all other connectors do)

### ISSUE THREAD

**Issue by oheyden** [CoreMedia/content-hub-adapter-dropbox#7]
Open Dropbox connector. Select an image  or a PDF or any file. In the details preview pane, no thumbnail is shown - only a standard image.
This is a bug as all other connectors do show an thumbnail at least in the details preview pane.
![2021-05-21_10h59_01](https://user-images.githubusercontent.com/895788/119111960-df6cc000-ba23-11eb-9199-f1b929e39935.png)

**Comment by sbuettne** [comment]
Fixed with release 1.0.5
